"""Add build_tags.

Revision ID: 9506d817d6e5
Revises: e16a8cd2e028
Create Date: 2021-07-08 11:27:04.677360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9506d817d6e5'
down_revision = 'e16a8cd2e028'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'build_tag',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('request_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['request_id'], ['request.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('build_tag', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_build_tag_request_id'), ['request_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('build_tag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_build_tag_request_id'))

    op.drop_table('build_tag')
    # ### end Alembic commands ###
